server:
  port: 8083
  

spring:
  application:
    name: VACCINE-CENTERS-SERVICE
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/SpringProject
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect